import { StyleSheet, Dimensions } from "react-native";
import { colors } from "@/constants/Colors";

const { width } = Dimensions.get('window');
const cardWidth = width * 0.85;

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    paddingTop: 60, // Add space for the header
    backgroundColor: 'transparent',
  },
  scrollContent: {
    paddingBottom: 30,
  },
  profileButton: {
    marginRight: 0,
  },
  welcomeSection: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 20,
  },
  welcomeText: {
    fontSize: 16,
    fontFamily: 'fontBold',
    color: colors.white,
    marginBottom: 4,
  },
  welcomeSubtext: {
    fontSize: 12,
    fontFamily: 'fontLight',
    color: 'rgba(255, 255, 255, 0.8)',
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 16,
    paddingHorizontal: 16,
    marginHorizontal: 20,
    marginBottom: 24,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    height: 50,
    color: '#333',
    fontFamily: 'fontLight',
    fontSize: 16,
  },
  statsContainer: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 14,
    fontFamily: 'fontBold',
    color: colors.white,
    marginBottom: 16,
  },
  statsScrollContent: {
    paddingRight: 20,
  },
  statsCard: {
    width: 150,
    height: 130,
    borderRadius: 10,
    padding: 16,
    marginRight: 12,
    flexDirection: 'column',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    alignItems: 'center',
  },
  statsIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  statsContent: {
    marginTop: 8,
    alignItems: 'center',
  },
  statsValue: {
    fontSize: 16,
    fontFamily: 'fontBold',
    color: colors.white,
    marginBottom: 4,
  },
  statsTitle: {
    fontSize: 12,
    fontFamily: 'fontBold',
    color: 'rgba(255, 255, 255, 0.8)',
  },
  specialtySection: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  specialtyFilterContainer: {
    paddingVertical: 8,
    paddingRight: 20,
  },
  specialtyItem: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    marginRight: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    borderWidth:1,
    borderColor:colors.green
  },
  specialtyItemSelected: {
    backgroundColor: colors.white,
  },
  specialtyText: {
    color: colors.white,
    fontSize: 14,
    fontFamily: 'fontLight',
  },
  specialtyTextSelected: {
    color: colors.primary,
    fontFamily: 'fontBold',
  },
  doctorsSection: {
    marginBottom: 30,
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  emptyText: {
    fontSize: 16,
    fontFamily: 'fontLight',
    color: colors.white,
    marginTop: 16,
  },
  doctorsContainer: {
    alignItems: 'center',
    width: '100%',
  },
  doctorCardContainer: {
    width: cardWidth,
    marginBottom: 20,
    borderRadius: 20,
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  doctorCard: {
    borderRadius: 20,
    overflow: 'hidden',
  },
  doctorCardGradient: {
    borderRadius: 20,
  },
  doctorCardContent: {
    padding: 16,
  },
  doctorHeader: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  doctorAvatarContainer: {
    marginRight: 16,
  },
  doctorAvatar: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  doctorAvatarText: {
    fontSize: 30,
    fontFamily: 'fontBold',
    color: colors.white,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  doctorInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  doctorName: {
    fontSize: 22,
    fontFamily: 'fontBold',
    color: colors.white,
    marginBottom: 4,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  doctorSpecialty: {
    fontSize: 16,
    fontFamily: 'fontLight',
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 8,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  starIcon: {
    marginRight: 2,
  },
  ratingText: {
    fontSize: 14,
    fontFamily: 'fontLight',
    color: 'rgba(255, 255, 255, 0.9)',
    marginLeft: 6,
  },
  doctorFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.2)',
  },
  feeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  feeText: {
    fontSize: 20,
    fontFamily: 'fontBold',
    color: colors.white,
    marginRight: 12,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  homeVisitTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  homeVisitText: {
    fontSize: 12,
    fontFamily: 'fontBold',
    color: colors.white,
    marginLeft: 6,
  },
  aiTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  aiTagText: {
    fontSize: 14,
    fontFamily: 'fontBold',
    color: colors.white,
    marginLeft: 6,
  },
  consultButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  consultButtonText: {
    color: colors.white,
    fontFamily: 'fontBold',
    fontSize: 16,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});
